### ISSUE TITLE
Expose Fastpack API

### ISSUE THREAD

**Issue by axetroy** [fastpack/fastpack#104]
Fastpack is very attractive to me because of the very fast speed.

I can use it instead of webpack to write my custom build system.

But unfortunately, it did not expose the API

```javascript
const fastpack = require('fastpack');

fastpack({ ...options })
  .then(() => {})
  .catch(() => {});
```

**Comment by zindel** [comment]
Hi @axetroy. Thanks for reporting the issue! In fact, exposing the JavaScript API is in our TODO list. We were not sure how high priority is it. It looks like it is getting higher in the list now :)
