### ISSUE TITLE
bundle/index.js has 600 permission instead of 644

### ISSUE THREAD

**Issue by brikou** [fastpack/fastpack#119]
When running fpack, the resulting file has 600 permission instead of 644. So the file is not readable by my nginx. Any idea on how to solve that (when using watch)?

thanks :)

**Comment by zindel** [comment]
Thank you for the report! Will be fixed in next release which we plan to have early next week.

**Comment by zindel** [comment]
A little later than I originally anticipated, but should be working :) Please try the latest `fpack` (0.6.0) from npm.

**Comment by brikou** [comment]
thanks
