### ISSUE TITLE
 libssl.so.1.1 error

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [fastpack/fastpack#130]
I'm trying to run fastpack on docker container node:8. But command `npx fpack --development <file>` returns me exit code 127.

Error message:
`fpack: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Any hints how to fix it?

**Comment by zindel** [comment]
Thank you for the report! I am planning to rework the release process for the next release. There will be statically pre-built binary for linux (which I guess will cover your case) and macos binary which points to the standard locations of the shared libs (should fix #127)

**Comment by zackferrofields** [comment]
Could this also be related to the very descriptive `node:alpine` error `not found`?

```
$ docker run -i -t node:8.11.1-alpine ash
$ cd ./tmp
$ yes "" | yarn init
$ yarn add fpack
$ ./node_modules/.bin/fpack -v
>> ash: ./node_modules/.bin/fpack: not found
```

```
$ docker run -i -t node:8.11.1 bash
$ cd ./tmp
$ yes "" | yarn init
$ yarn add fpack
$ ./node_modules/.bin/fpack -v
>> ./node_modules/.bin/fpack: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by zindel** [comment]
@przemyslawjanpietrzak @zackferrofields I've just released the `fpack@0.6.4` to npm. It contains the statically linked linux binary. Could you plz confirm if it works for you?

**Comment by zackferrofields** [comment]
@zindel I've just tested this on ` node:8.11.1-alpine` and it works 🎉

**Comment by zindel** [comment]
Ok, closing this one. Mac's issue still remains though :(
