### ISSUE TITLE
Add the ability to inject environment variables into the final bundle

### ISSUE THREAD

**Issue by johnhaley81** [fastpack/fastpack#148]
Currently, we use environment variables to point to staging/production and there's no way to do this right now with fastpack. Having this would allow us to make the switch 😁

**Comment by zindel** [comment]
@johnhaley81 Thank you for reporting it! One addition which could be helpful if you can provide some examples of how are you using that? Is it assuming code inlining and prune unreachable branches like this:

```JavaScript
let x = process.env.MY_VAR === "xxx" ? doSomething() : doSomethingElse
```
=>
```JavaScript
let x = doSomething();
```

Are there any other usage scenarios?

**Comment by johnhaley81** [comment]
We aren't doing anything else besides the above subject I if that worked it would solve our use case.

**Comment by bpierre** [comment]
@johnhaley81 In case you are already using babel, this plugin can help: https://babeljs.io/docs/en/babel-plugin-transform-inline-environment-variables

**Comment by zindel** [comment]
@johnhaley81 done. Please, check the `fastpack@0.8.4`. Feel free to reopen if it doesn't work well :)
