### ISSUE TITLE
0.7.0 and 0.8.0 npm releases

### ISSUE THREAD

**Issue by bpierre** [fastpack/fastpack#150]
Thanks for fastpack!

Could we get 0.8.0 (and 0.7.0?) on npm?

**Comment by andreypopp** [comment]
See `fastpack` package on npm!

**Comment by zindel** [comment]
Just leaving this link here :) (fastpack)[https://www.npmjs.com/package/fastpack]

**Comment by TrySound** [comment]
@zindel Need to tweak readme I believe

**Comment by zindel** [comment]
@TrySound good catch! Fixed

**Comment by bpierre** [comment]
Awesome thanks!
