### ISSUE TITLE
JSX is not fully transpiled

### ISSUE THREAD

**Issue by TrySound** [fastpack/fastpack#20]
1. JSX is not transpiled if react is imported like this
```js
import * as React from 'react';

const App = ({ components }) => (
  <div>
    {components.map((Comp, i) => (
      <div key={i}>
        <Comp />
      </div>
    ))}
  </div>
);
```
Which is more correct since flow definition are namespaced

2. JSX is not transpiled inside function
```js
const $lib1 = __fastpack_require__(/* "react" */ "NM$$react$index");
const $lib2 = __fastpack_require__(/* "react-dom" */ "NM$$react$$_$$dom$index");
const App = ({components}) =>  $lib1.createElement("div", null, components.map((Comp, i) =>  <div
  key={i}>
        <Comp/>
      </div>));
```

**Comment by zindel** [comment]
@TrySound thank you for reporting it. The second part is fixed with commit above. I cannot reproduce the first part though on the latest master. Could you try it out with it? Please note, that `--transpile` has been renamed to `--preprocess`. Otherwise it should be fine.

**Comment by TrySound** [comment]
@zindel I found fpack can't transpile if I pass entry point as absolute path

**Comment by zindel** [comment]
@TrySound this is likely to be fixed in master branch as well. Mind trying to rebuild and retry?

**Comment by TrySound** [comment]
@zindel Yep, it happens with that change. jsx in map is fixed.

**Comment by zindel** [comment]
@TrySound, ok, let me look at it right now

**Comment by TrySound** [comment]
Problems are solved
