### ISSUE TITLE
Verify compatibility with the popular webpack loaders

### ISSUE THREAD

**Issue by zindel** [fastpack/fastpack#41]
- [x] raw-loader
- [x] babel-loader
- [x] url-loader
- [x] file-loader
- [x] css-loader
- [x] style-loader
- [x] postcss-loader

The next 3 are optional for the first release, but may be useful:
- [x] ts-loader
- [ ] sass-loader
- [ ] less-loader

**Comment by zindel** [comment]
It would be great to create the fpack-loader-bridge npm package, which will include the 'loader-runner' as well as those 7 top common loaders with versions which are tested with the Fastpack. In this case we will be recommending installing this only package in order to handle CSS and/or static files.

Thoughts? cc @andreypopp @TrySound @rauanmayemir

**Comment by andreypopp** [comment]
I don't think this is needed — `loader-runner` package is pretty stable afaik — loader API didn't change for quite a while. Let's not make it more complicated than with webpack where we can just install loaders alone. It's a good idea to have e2e tests with those loaders though.

**Comment by zindel** [comment]
we do have those tests. See `test/pack-{sass,less,cra,raw,custom-loader}`. Although, the last piece of them (i.e. making sure it works in browser) is still manual
