### ISSUE TITLE
Rename output file?

### ISSUE THREAD

**Issue by gilbert** [fastpack/fastpack#80]
I noticed fpack's generated output is always `index.js`. Is there a way to name it differently, perhaps based on the original file name?

**Comment by zindel** [comment]
Hi @gilbert! Thanks for reporting the issue!

The short answer to your question is "no" at the moment. Fastpack produces only one bundle file with the pre-defined name `<output directory>/index.js`. The reason for it is that, in fact, we don't generate chunked bundles yet, so we just picked it and let it be.

Maybe, this is a good time to review it, and see how we can do better. This is what webpack does for it: https://webpack.js.org/configuration/output/#output-filename. I.e. it is possible to use template to specify the output name, include hash etc. We could look into this direction as well, although I would prefer to keep it as simple as possible, until it is needed.

I see 2 main use cases with the regard to the main bundle name:
1. **JavaScript-first**. I.e. HTML page can adapt to what bundler has produced, pick generated name and include it into the `<script/>` tag and/or load it in some other way. In this case I would make the output file names be the bundler implementation detail and produce the `manifest.json` file, from which the required name could be extracted.
1. **HTML-first**. HTML page is stable and main JavaScript file name is known in advance. In this case fastpack should be provided with the desired name and should respect it when producing the main bundle file. Other filenames (chunks, static files, etc) should remain under the bundler control and considered the implementation details.

Technically speaking the current fastpack implementation mostly covers the first case (with an exception of the `manifest.json`), but fails in the second one. To fulfil it we can add the `--output-file` option accepting the plain filename. Would it work for your case?

It could be the "good first task" kind of thing, so if you're interested in filling the PR, I'm happy to introduce you to the code.

**Comment by zindel** [comment]
@gilbert thank you for the implementation! Closing the issue
