### ISSUE TITLE
Resolve node_modules recursively to the root

### ISSUE THREAD

**Issue by TrySound** [fastpack/fastpack#84]
Currently node_modules are resolved only until project root. This is incorrect behaviour for the ecosystem.

For example workspaces rely on it to hoist node_modules in monorepo to the root. Here's example
```
package.json
node_modules
project-1
- package.json
- node_modules
project-2
- package.json
- node_modules
packages/
- reusable
-- package.json
-- node_modules
```

[Node resolve algorithm](https://nodejs.org/dist/latest-v8.x/docs/api/modules.html#modules_all_together)

**Comment by zindel** [comment]
@TrySound let's close this issue then and create the new one specifying the `--project-root` requirements?

**Comment by TrySound** [comment]
Sure. Open please. I will take a look later.

**Comment by sibelius** [comment]
is this fixed?

**Comment by TrySound** [comment]
@sibelius Yes, https://fastpack.sh/docs/configuration.html#project-root
