### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Easte-r** [fastpack/fastpack#97]
I'm running npm install -g fpack, but got error

> fpack@0.5.2 postinstall C:\Program Files\nodejs\node_modules\fpack
> make --silent --no-print-directory installound in:
make is not a program or bat file

my operating system is windows , node version is v8.9.4

**Comment by zindel** [comment]
Hi! Thank you for submitting an issue. Windows is not supported yet, but we'll be actively working on fixing this quite soon.

**Comment by zindel** [comment]
Just published `fastpack@0.7.0` which has Windows support. Closing this one. Thanks again, @bryphe for all your help!

**Comment by bryphe** [comment]
Wow, awesome @zindel ! 🎉 🎉 Very exciting!

**Comment by samouri** [comment]
That is awesome. I'm excited to test this out later

**Comment by zindel** [comment]
@samouri Thank you! I'm especially curious about build times. I've been working on it in VirtualBox VM, so didn't see real numbers
